import type { ReviewConfig } from './schema.js';

export const DEFAULT_CONFIG: ReviewConfig = {
  language: 'en',
  provider: 'kimi',
  model: 'kimi-k2.5',
  review: {
    auto: {
      enabled: true,
      onOpen: true,
      onPush: true,
      onReviewRequest: true,
      drafts: false,
    },
    aspects: {
      bugs: true,
      security: true,
      performance: true,
      style: true,
      bestPractices: true,
      documentation: false,
      testing: false,
    },
    minSeverity: 'suggestion',
    maxAnnotations: 30,
    failOn: 'critical',
  },
  files: {
    include: ['**/*'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/*.lock',
      '**/*.min.*',
      '**/package-lock.json',
      '**/yarn.lock',
      '**/pnpm-lock.yaml',
    ],
    maxFileSize: 100_000,
  },
  rules: [],
  prompt: {},
  cache: {
    enabled: true,
    ttl: 3600,
  },
  pipeline: {
    enabled: true,
    concurrency: 3,
    groupTokenBudget: 40_000,
    relatedContextBudget: 15_000,
    maxGroups: 8,
    fastPathThreshold: 25_000,
    minConfidence: 0.6,
    maxRetries: 3,
    callTimeoutMs: 120_000,
    maxOutputTokens: 8_192,
  },
};
