import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, '..');
const templatePath = resolve(repositoryRoot, 'src/pipeline/templates/change-diagram.md');
const generatedPath = resolve(repositoryRoot, 'src/pipeline/generated/change-diagram-prompt.ts');

const template = await readFile(templatePath, 'utf8');
const generated = `// Generated by scripts/embed-prompts.mjs; do not edit.\nexport const CHANGE_DIAGRAM_PROMPT = ${JSON.stringify(template)};\n`;

await mkdir(dirname(generatedPath), { recursive: true });
let existing;
try {
  existing = await readFile(generatedPath, 'utf8');
} catch (error) {
  if (error?.code !== 'ENOENT') throw error;
}

if (existing !== generated) {
  await writeFile(generatedPath, generated, 'utf8');
}
